### PR TITLE
Add tags to series

### PR DESCRIPTION
**Pull request by flowbehappy**
Seems series object missing tags result, add it for consistent.

### CODE REVIEW

**Comment by majst01** [comment]
Can you show me a query which returns a result which includes tags please ?

**Comment by flowbehappy** [comment]
@majst01 Of course! My app really depends on those tags.

```
[14:20:10] flow@FLOW-MBP ~  $ curl -G 'http://192.168.10.51:8086/query?u=root&p=root&db=dcmonitor&pretty=true' --data-urlencode "q=select * f
rom kafka_metrics limit 2"
{
    "results": [
        {
            "series": [
                {
                    "name": "kafka_metrics",
                    "tags": {
                        "consumer": "clicki_mysql_ingester_0",
                        "partition": "-1",
                        "topic": "clicki_stat_topic"
                    },
                    "columns": [
                        "time",
                        "lag",
                        "offs",
                        "size"
                    ],
                    "values": [
                        [
                            "2015-07-02T04:00:38.544Z",
                            0,
                            132900,
                            132900
                        ],
                        [
                            "2015-07-02T04:00:43.879Z",
                            0,
                            132900,
                            132900
                        ]
                    ]
                },
                {
                    "name": "kafka_metrics",
                    "tags": {
                        "consumer": "clicki_mysql_ingester_0",
                        "partition": "0",
                        "topic": "clicki_stat_topic"
                    },
                    "columns": [
                        "time",
                        "lag",
                        "offs",
                        "size"
                    ],
                    "values": [
                        [
                            "2015-07-02T04:00:38.544Z",
                            0,
                            82934,
                            82934
                        ],
                        [
                            "2015-07-02T04:00:43.879Z",
                            0,
                            82934,
                            82934
                        ]
                    ]
                },
                {
                    "name": "kafka_metrics",
                    "tags": {
                        "consumer": "clicki_mysql_ingester_0",
                        "partition": "1",
                        "topic": "clicki_stat_topic"
                    },
                    "columns": [
                        "time",
                        "lag",
                        "offs",
                        "size"
                    ],
                    "values": [
                        [
                            "2015-07-02T04:00:38.544Z",
                            0,
                            9,
                            9
                        ],
                        [
                            "2015-07-02T04:00:43.879Z",
                            0,
                            9,
                            9
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by andremann** [comment]
I also find this vital for the application I'm designing. +1

**Comment by majst01** [comment]
I guess we need another approach,

- Create a new DTO SeriesQueryResult which exactly matches the result comming from influxdb on such a query, including name, tags, columns and values.
- Add a new Method to InfluxDB for example querySerie which returns this DTO

What do you think ?
Stefan

**Comment by andremann** [comment]
It seems a viable solution.. However I don't get why not putting tags directly in the inner inner class Series as proposed in the PR by @flowbehappy.

**Comment by majst01** [comment]
I tried your approach and i like it :-)

**Pull request merged**
